config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :speaks do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/speak.rb
class Speak < ApplicationRecord
  validates :content, length: {in:1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/speaks_controller.rb
class SpeaksController < ApplicationController
  before_action :set_speak, only: [:edit, :update, :destroy]

  def index
    @speaks = Speak.all
  end

  def new
    @speak = Speak.new
  end

  def create
    @speak = Speak.new(speak_params)
    if params[:back]
      render :new

    else
      if @speak.save
        redirect_to speaks_path, notice: "投稿しました！"
      else
        render 'new'
      end
    end
  end

  def edit
  end

  def update
    if @speak.update(speak_params)
      redirect_to speaks_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @speak.destroy
    redirect_to speaks_path, notice: "削除しました！"
  end


  def confirm
    @speak = Speak.new(speak_params)
    render :new if @speak.invalid?
  end

  private

  def speak_params
    params.require(:speak).permit(:content)
  end

  def set_speak
    @speak = Speak.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/speaks_helper.rb
module SpeaksHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_speaks_path
    elsif action_name == 'edit'
      speak_path
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hitokoto</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div id="wrapper">
    <header>ひとこと</header>
    <%= yield %>
    <footer>ひとこと</footer>
  </div>
</body>
</html>

app/views/speaks/_form.html.erb
<%= form_with(model: @speak, local: true, url: choose_new_or_edit) do |form| %>
<% if @speak.errors.any? %>
<h1><%= @speak.errors.count %>件のエラーがあります。</h1>
<ul>
  <% @speak.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form.text_area :content, rows: 10, cols:50 %><br>
<%= form.submit %><br>

<% end %>
<%= link_to '【topに戻る】', root_path %>

app/views/speaks/confirm.html.erb
<h1>確認画面</h1>

<%= form_with(model:@speak, local: true) do |form| %>
<%= form.hidden_field :content %>

<p>本文:<%= @speak.content %></p>

<%= form.submit "登録する" %>
<%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/speaks/edit.html.erb
<h1>編集画面</h1>

<%= render 'form' %>

<%= link_to '【一覧に戻る】', speaks_path %>

app/views/speaks/index.html.erb
<h1>一覧表示</h1>

<p><%= notice %></p>

<table border="1" align="center">
  <colgroup>
    <col style="width:60%">
    <col style="width:20%">
    <col style="width:20%">
  </colgroup>


  <% @speaks.each do |speak| %>
  <tr>
    <td><%= speak.content %></td>
    <td><%= link_to "編集する", edit_speak_path(speak.id), data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to '削除する', speak_path(speak.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
  <% end %>
</table>

<%= link_to '【topに戻る】', root_path %>

app/views/speaks/new.html.erb
<h1>新規投稿</h1>

<%= render 'form' %>

app/views/welcome/index.html.erb
<h1>Let's type!</h1>

<p>1~140文字をつぶやこう！</p>
<img src = "duck.jpg"><br>

<%= link_to '【新規投稿】', new_speak_path %>
<%= link_to '【一覧表示】', speaks_path %>